# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stskeygen < Formula
  desc "A commandline utility for trading directory service credentials (such as AD username and password) for AWS STS Keys."
  homepage "https://cimpress-support.atlassian.net/wiki/spaces/CloudKB/pages/15058567646/Generating+STS+access+keys+via+Auth0"
  version "2.5.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://ce-installation-binaries.s3.us-east-1.amazonaws.com/stskeygen/2.5.3/stskeygen_2.5.3_darwin_arm64.tar.gz"
      sha256 "0bf3a0b3a44ba20b7f9fa85310cebebe1324fcc96685ce6136a12ccc78f31e5e"

      def install
        bin.install "stskeygen"
      end
    end
    if Hardware::CPU.intel?
      url "https://ce-installation-binaries.s3.us-east-1.amazonaws.com/stskeygen/2.5.3/stskeygen_2.5.3_darwin_amd64.tar.gz"
      sha256 "0160644ce60694f74e4e8491ed0a4559b7563963043e75d667079fbf8fe7b6e3"

      def install
        bin.install "stskeygen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://ce-installation-binaries.s3.us-east-1.amazonaws.com/stskeygen/2.5.3/stskeygen_2.5.3_linux_arm64.tar.gz"
      sha256 "92e70bae871bb727b373b6117dfe4198c4995b3df6694c99385d121c46aec54f"

      def install
        bin.install "stskeygen"
      end
    end
    if Hardware::CPU.intel?
      url "https://ce-installation-binaries.s3.us-east-1.amazonaws.com/stskeygen/2.5.3/stskeygen_2.5.3_linux_amd64.tar.gz"
      sha256 "f08262230d43f8a18a4c136f8905254d7f3dafd943e37f70bc090e58863ad77e"

      def install
        bin.install "stskeygen"
      end
    end
  end

  test do
    system "#{bin}/stskeygen"
  end
end
