# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stskeygen < Formula
  desc "A commandline utility for trading directory service credentials (such as AD username and password) for AWS STS Keys."
  homepage "https://cimpress-support.atlassian.net/wiki/spaces/CloudKB/pages/15058567646/Generating+STS+access+keys+via+Auth0"
  version "2.4.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://ce-installation-binaries.s3.us-east-1.amazonaws.com/stskeygen/2.4.3/stskeygen_2.4.3_darwin_amd64.tar.gz"
      sha256 "402f53934040fcaf5a0346f2b66a6b2c1f5232f923f6fa4c60f1400a6d7f0105"

      def install
        bin.install "stskeygen"
      end
    end
    if Hardware::CPU.arm?
      url "https://ce-installation-binaries.s3.us-east-1.amazonaws.com/stskeygen/2.4.3/stskeygen_2.4.3_darwin_arm64.tar.gz"
      sha256 "04f2f42d9dee0ab4646d829a6c94b019d47cbfddfbc433c786c371ec3f0b521e"

      def install
        bin.install "stskeygen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://ce-installation-binaries.s3.us-east-1.amazonaws.com/stskeygen/2.4.3/stskeygen_2.4.3_linux_arm64.tar.gz"
      sha256 "d8279b72e9b57458851d2a73374338e91f44327cc2dacea8a812423cd5cd765a"

      def install
        bin.install "stskeygen"
      end
    end
    if Hardware::CPU.intel?
      url "https://ce-installation-binaries.s3.us-east-1.amazonaws.com/stskeygen/2.4.3/stskeygen_2.4.3_linux_amd64.tar.gz"
      sha256 "372a743f8388fe3e494ba7348b470fa0273bd467770d0d2a58292ed141244bca"

      def install
        bin.install "stskeygen"
      end
    end
  end

  test do
    system "#{bin}/stskeygen"
  end
end
